# name: Build Image Frontend

# on:
#   workflow_call:
#     secrets:

#       DOCKER_HUB_ACCESS_TOKEN:
#         required: true

# jobs:
#   build-image:
#     name: Build and Push Docker Image
#     runs-on: ubuntu-latest
#     steps:
#         - name: Build Docker Image
#           uses: docker/build-push-action@v5.3.0
#           with:
#             push: false
#             tags: datuits/devops-frontend:latest

#         - name: Login to Docker Hub
#           uses: docker/login-action@v1
#           with:
#             username: datuits
#             password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#         - name: Push to Docker Hub
#           uses: docker/build-push-action@v2
#           with:
#             push: true
#             tags: datuits/devops-frontend:latest